// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tools.proto

package com.survey.protobuf.proto;

public final class ToolsProto {
  private ToolsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimpleListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated bytes elements = 1;
    java.util.List<com.google.protobuf.ByteString> getElementsList();
    int getElementsCount();
    com.google.protobuf.ByteString getElements(int index);
  }
  public static final class SimpleList extends
      com.google.protobuf.GeneratedMessage
      implements SimpleListOrBuilder {
    // Use SimpleList.newBuilder() to construct.
    private SimpleList(Builder builder) {
      super(builder);
    }
    private SimpleList(boolean noInit) {}
    
    private static final SimpleList defaultInstance;
    public static SimpleList getDefaultInstance() {
      return defaultInstance;
    }
    
    public SimpleList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_SimpleList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_SimpleList_fieldAccessorTable;
    }
    
    // repeated bytes elements = 1;
    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> elements_;
    public java.util.List<com.google.protobuf.ByteString>
        getElementsList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public com.google.protobuf.ByteString getElements(int index) {
      return elements_.get(index);
    }
    
    private void initFields() {
      elements_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < elements_.size(); i++) {
        output.writeBytes(1, elements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < elements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(elements_.get(i));
        }
        size += dataSize;
        size += 1 * getElementsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.SimpleList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.survey.protobuf.proto.ToolsProto.SimpleList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.survey.protobuf.proto.ToolsProto.SimpleListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_SimpleList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_SimpleList_fieldAccessorTable;
      }
      
      // Construct using com.survey.protobuf.proto.ToolsProto.SimpleList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.survey.protobuf.proto.ToolsProto.SimpleList.getDescriptor();
      }
      
      public com.survey.protobuf.proto.ToolsProto.SimpleList getDefaultInstanceForType() {
        return com.survey.protobuf.proto.ToolsProto.SimpleList.getDefaultInstance();
      }
      
      public com.survey.protobuf.proto.ToolsProto.SimpleList build() {
        com.survey.protobuf.proto.ToolsProto.SimpleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.survey.protobuf.proto.ToolsProto.SimpleList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.survey.protobuf.proto.ToolsProto.SimpleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.survey.protobuf.proto.ToolsProto.SimpleList buildPartial() {
        com.survey.protobuf.proto.ToolsProto.SimpleList result = new com.survey.protobuf.proto.ToolsProto.SimpleList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.survey.protobuf.proto.ToolsProto.SimpleList) {
          return mergeFrom((com.survey.protobuf.proto.ToolsProto.SimpleList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.survey.protobuf.proto.ToolsProto.SimpleList other) {
        if (other == com.survey.protobuf.proto.ToolsProto.SimpleList.getDefaultInstance()) return this;
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureElementsIsMutable();
              elements_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated bytes elements = 1;
      private java.util.List<com.google.protobuf.ByteString> elements_ = java.util.Collections.emptyList();;
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new java.util.ArrayList<com.google.protobuf.ByteString>(elements_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getElementsList() {
        return java.util.Collections.unmodifiableList(elements_);
      }
      public int getElementsCount() {
        return elements_.size();
      }
      public com.google.protobuf.ByteString getElements(int index) {
        return elements_.get(index);
      }
      public Builder setElements(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addElements(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
        return this;
      }
      public Builder clearElements() {
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:SimpleList)
    }
    
    static {
      defaultInstance = new SimpleList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:SimpleList)
  }
  
  public interface IntListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int32 elements = 1 [packed = true];
    java.util.List<java.lang.Integer> getElementsList();
    int getElementsCount();
    int getElements(int index);
  }
  public static final class IntList extends
      com.google.protobuf.GeneratedMessage
      implements IntListOrBuilder {
    // Use IntList.newBuilder() to construct.
    private IntList(Builder builder) {
      super(builder);
    }
    private IntList(boolean noInit) {}
    
    private static final IntList defaultInstance;
    public static IntList getDefaultInstance() {
      return defaultInstance;
    }
    
    public IntList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_IntList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_IntList_fieldAccessorTable;
    }
    
    // repeated int32 elements = 1 [packed = true];
    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> elements_;
    public java.util.List<java.lang.Integer>
        getElementsList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public int getElements(int index) {
      return elements_.get(index);
    }
    private int elementsMemoizedSerializedSize = -1;
    
    private void initFields() {
      elements_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getElementsList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(elementsMemoizedSerializedSize);
      }
      for (int i = 0; i < elements_.size(); i++) {
        output.writeInt32NoTag(elements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < elements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(elements_.get(i));
        }
        size += dataSize;
        if (!getElementsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        elementsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.IntList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.survey.protobuf.proto.ToolsProto.IntList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.survey.protobuf.proto.ToolsProto.IntListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_IntList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_IntList_fieldAccessorTable;
      }
      
      // Construct using com.survey.protobuf.proto.ToolsProto.IntList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.survey.protobuf.proto.ToolsProto.IntList.getDescriptor();
      }
      
      public com.survey.protobuf.proto.ToolsProto.IntList getDefaultInstanceForType() {
        return com.survey.protobuf.proto.ToolsProto.IntList.getDefaultInstance();
      }
      
      public com.survey.protobuf.proto.ToolsProto.IntList build() {
        com.survey.protobuf.proto.ToolsProto.IntList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.survey.protobuf.proto.ToolsProto.IntList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.survey.protobuf.proto.ToolsProto.IntList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.survey.protobuf.proto.ToolsProto.IntList buildPartial() {
        com.survey.protobuf.proto.ToolsProto.IntList result = new com.survey.protobuf.proto.ToolsProto.IntList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.survey.protobuf.proto.ToolsProto.IntList) {
          return mergeFrom((com.survey.protobuf.proto.ToolsProto.IntList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.survey.protobuf.proto.ToolsProto.IntList other) {
        if (other == com.survey.protobuf.proto.ToolsProto.IntList.getDefaultInstance()) return this;
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureElementsIsMutable();
              elements_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addElements(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 elements = 1 [packed = true];
      private java.util.List<java.lang.Integer> elements_ = java.util.Collections.emptyList();;
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new java.util.ArrayList<java.lang.Integer>(elements_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getElementsList() {
        return java.util.Collections.unmodifiableList(elements_);
      }
      public int getElementsCount() {
        return elements_.size();
      }
      public int getElements(int index) {
        return elements_.get(index);
      }
      public Builder setElements(
          int index, int value) {
        ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addElements(int value) {
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
        return this;
      }
      public Builder clearElements() {
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:IntList)
    }
    
    static {
      defaultInstance = new IntList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:IntList)
  }
  
  public interface LongListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int64 elements = 1 [packed = true];
    java.util.List<java.lang.Long> getElementsList();
    int getElementsCount();
    long getElements(int index);
  }
  public static final class LongList extends
      com.google.protobuf.GeneratedMessage
      implements LongListOrBuilder {
    // Use LongList.newBuilder() to construct.
    private LongList(Builder builder) {
      super(builder);
    }
    private LongList(boolean noInit) {}
    
    private static final LongList defaultInstance;
    public static LongList getDefaultInstance() {
      return defaultInstance;
    }
    
    public LongList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_LongList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_LongList_fieldAccessorTable;
    }
    
    // repeated int64 elements = 1 [packed = true];
    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> elements_;
    public java.util.List<java.lang.Long>
        getElementsList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public long getElements(int index) {
      return elements_.get(index);
    }
    private int elementsMemoizedSerializedSize = -1;
    
    private void initFields() {
      elements_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getElementsList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(elementsMemoizedSerializedSize);
      }
      for (int i = 0; i < elements_.size(); i++) {
        output.writeInt64NoTag(elements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < elements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(elements_.get(i));
        }
        size += dataSize;
        if (!getElementsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        elementsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.LongList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.survey.protobuf.proto.ToolsProto.LongList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.survey.protobuf.proto.ToolsProto.LongListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_LongList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_LongList_fieldAccessorTable;
      }
      
      // Construct using com.survey.protobuf.proto.ToolsProto.LongList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.survey.protobuf.proto.ToolsProto.LongList.getDescriptor();
      }
      
      public com.survey.protobuf.proto.ToolsProto.LongList getDefaultInstanceForType() {
        return com.survey.protobuf.proto.ToolsProto.LongList.getDefaultInstance();
      }
      
      public com.survey.protobuf.proto.ToolsProto.LongList build() {
        com.survey.protobuf.proto.ToolsProto.LongList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.survey.protobuf.proto.ToolsProto.LongList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.survey.protobuf.proto.ToolsProto.LongList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.survey.protobuf.proto.ToolsProto.LongList buildPartial() {
        com.survey.protobuf.proto.ToolsProto.LongList result = new com.survey.protobuf.proto.ToolsProto.LongList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = java.util.Collections.unmodifiableList(elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.survey.protobuf.proto.ToolsProto.LongList) {
          return mergeFrom((com.survey.protobuf.proto.ToolsProto.LongList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.survey.protobuf.proto.ToolsProto.LongList other) {
        if (other == com.survey.protobuf.proto.ToolsProto.LongList.getDefaultInstance()) return this;
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureElementsIsMutable();
              elements_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addElements(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int64 elements = 1 [packed = true];
      private java.util.List<java.lang.Long> elements_ = java.util.Collections.emptyList();;
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new java.util.ArrayList<java.lang.Long>(elements_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Long>
          getElementsList() {
        return java.util.Collections.unmodifiableList(elements_);
      }
      public int getElementsCount() {
        return elements_.size();
      }
      public long getElements(int index) {
        return elements_.get(index);
      }
      public Builder setElements(
          int index, long value) {
        ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addElements(long value) {
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
        return this;
      }
      public Builder clearElements() {
        elements_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LongList)
    }
    
    static {
      defaultInstance = new LongList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LongList)
  }
  
  public interface StringListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string elements = 1;
    java.util.List<String> getElementsList();
    int getElementsCount();
    String getElements(int index);
  }
  public static final class StringList extends
      com.google.protobuf.GeneratedMessage
      implements StringListOrBuilder {
    // Use StringList.newBuilder() to construct.
    private StringList(Builder builder) {
      super(builder);
    }
    private StringList(boolean noInit) {}
    
    private static final StringList defaultInstance;
    public static StringList getDefaultInstance() {
      return defaultInstance;
    }
    
    public StringList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_StringList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.survey.protobuf.proto.ToolsProto.internal_static_StringList_fieldAccessorTable;
    }
    
    // repeated string elements = 1;
    public static final int ELEMENTS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList elements_;
    public java.util.List<String>
        getElementsList() {
      return elements_;
    }
    public int getElementsCount() {
      return elements_.size();
    }
    public String getElements(int index) {
      return elements_.get(index);
    }
    
    private void initFields() {
      elements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < elements_.size(); i++) {
        output.writeBytes(1, elements_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < elements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(elements_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getElementsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.survey.protobuf.proto.ToolsProto.StringList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.survey.protobuf.proto.ToolsProto.StringList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.survey.protobuf.proto.ToolsProto.StringListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_StringList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.survey.protobuf.proto.ToolsProto.internal_static_StringList_fieldAccessorTable;
      }
      
      // Construct using com.survey.protobuf.proto.ToolsProto.StringList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        elements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.survey.protobuf.proto.ToolsProto.StringList.getDescriptor();
      }
      
      public com.survey.protobuf.proto.ToolsProto.StringList getDefaultInstanceForType() {
        return com.survey.protobuf.proto.ToolsProto.StringList.getDefaultInstance();
      }
      
      public com.survey.protobuf.proto.ToolsProto.StringList build() {
        com.survey.protobuf.proto.ToolsProto.StringList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.survey.protobuf.proto.ToolsProto.StringList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.survey.protobuf.proto.ToolsProto.StringList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.survey.protobuf.proto.ToolsProto.StringList buildPartial() {
        com.survey.protobuf.proto.ToolsProto.StringList result = new com.survey.protobuf.proto.ToolsProto.StringList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new com.google.protobuf.UnmodifiableLazyStringList(
              elements_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elements_ = elements_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.survey.protobuf.proto.ToolsProto.StringList) {
          return mergeFrom((com.survey.protobuf.proto.ToolsProto.StringList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.survey.protobuf.proto.ToolsProto.StringList other) {
        if (other == com.survey.protobuf.proto.ToolsProto.StringList.getDefaultInstance()) return this;
        if (!other.elements_.isEmpty()) {
          if (elements_.isEmpty()) {
            elements_ = other.elements_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElementsIsMutable();
            elements_.addAll(other.elements_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureElementsIsMutable();
              elements_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string elements = 1;
      private com.google.protobuf.LazyStringList elements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          elements_ = new com.google.protobuf.LazyStringArrayList(elements_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getElementsList() {
        return java.util.Collections.unmodifiableList(elements_);
      }
      public int getElementsCount() {
        return elements_.size();
      }
      public String getElements(int index) {
        return elements_.get(index);
      }
      public Builder setElements(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureElementsIsMutable();
        elements_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addElements(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllElements(
          java.lang.Iterable<String> values) {
        ensureElementsIsMutable();
        super.addAll(values, elements_);
        onChanged();
        return this;
      }
      public Builder clearElements() {
        elements_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addElements(com.google.protobuf.ByteString value) {
        ensureElementsIsMutable();
        elements_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:StringList)
    }
    
    static {
      defaultInstance = new StringList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:StringList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SimpleList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IntList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IntList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LongList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LongList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StringList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/tools.proto\"\036\n\nSimpleList\022\020\n\010ele" +
      "ments\030\001 \003(\014\"\037\n\007IntList\022\024\n\010elements\030\001 \003(\005" +
      "B\002\020\001\" \n\010LongList\022\024\n\010elements\030\001 \003(\003B\002\020\001\"\036" +
      "\n\nStringList\022\020\n\010elements\030\001 \003(\tB\'\n\031com.su" +
      "rvey.protobuf.protoB\nToolsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SimpleList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SimpleList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SimpleList_descriptor,
              new java.lang.String[] { "Elements", },
              com.survey.protobuf.proto.ToolsProto.SimpleList.class,
              com.survey.protobuf.proto.ToolsProto.SimpleList.Builder.class);
          internal_static_IntList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_IntList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IntList_descriptor,
              new java.lang.String[] { "Elements", },
              com.survey.protobuf.proto.ToolsProto.IntList.class,
              com.survey.protobuf.proto.ToolsProto.IntList.Builder.class);
          internal_static_LongList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_LongList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LongList_descriptor,
              new java.lang.String[] { "Elements", },
              com.survey.protobuf.proto.ToolsProto.LongList.class,
              com.survey.protobuf.proto.ToolsProto.LongList.Builder.class);
          internal_static_StringList_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_StringList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StringList_descriptor,
              new java.lang.String[] { "Elements", },
              com.survey.protobuf.proto.ToolsProto.StringList.class,
              com.survey.protobuf.proto.ToolsProto.StringList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
